#!/bin/bash
killall Xvfb
killall sbcl
killall emacs
killall x11vnc
killall fluxbox

export DISPLAY=:35
nohup Xvfb $DISPLAY -screen 0 1024x768x16 -shmem 2>&1 | awk -W interactive '{ print $4 }' > shared-memory-id &
sleep 2
x11vnc -display $DISPLAY -env FD_PROG=/usr/bin/fluxbox \
    -env X11VNC_FINDDISPLAY_ALWAYS_FAILS=1 \
        -env X11VNC_CREATE_GEOM=${1:-1024x768x16} \
        -gone 'killall Xvfb' \
        -bg -nopw &
fluxbox &
nohup ~/portacle/portacle.run &






#nohup Xvfb $DISPLAY -screen 0 1024x768x16 -shmem 2>&1  &
#sleep 1
#fluxbox &
#~/portacle/portacle.run &
#x11vnc -display $DISPLAY -bg -forever -nopw -quiet -listen localhost -xkb


#echo shared-memory-id
#steam_runtime=/home/selwyn/.steam/ubuntu12_32/steam-runtime/run.sh
#$steam_runtime sbcl --eval "(defparameter *shared-memory-id* 100)" \
#                    --eval '(ql:quickload :swank)' \
#                    --eval "(swank:create-server :port ${port:-4005} :dont-close t)" \
#                    --eval "(uiop:launch-program \"vncviewer localhost:5900\")"
#sleep 2
#echo before vncviewer
#vncviewer localhost:5900
#echo after vncviewer


#killall Xvfb
#killall sbcl
#killall emacs 
