#!/bin/bash
killall Xvfb
killall sbcl
killall emacs
killall x11vnc
killall fluxbox

export DISPLAY=:35
nohup Xvfb $DISPLAY -screen 0 1024x768x16 -shmem 2>&1 | awk -W interactive '{ print $4 }' > shared-memory-id &
sleep 2
x11vnc -display $DISPLAY -env FD_PROG=/usr/bin/fluxbox \
    -env X11VNC_FINDDISPLAY_ALWAYS_FAILS=1 \
        -env X11VNC_CREATE_GEOM=${1:-1024x768x16} \
        -gone 'killall Xvfb' \
        -bg -nopw &
fluxbox &
nohup ~/portacle/portacle.run &
